### ISSUE TITLE
Getting an Error Code 3 from the disk DSR when accessing Google Drive

### ISSUE THREAD

**Issue by 0x1DEACAFE** [Rasmus-M/js99er-angular#1]
If I do something like this in regular TI BASIC

    100 OPEN #1:"GDR1.BASE01",RELATIVE,INTERNAL,INPUT,FIXED
    110 IF EOF(1) THEN 150
    ...
    150 CLOSE #1

I get an I/O Error 93.

I tried it with several other options (SEQUENTIAL, DISPLAY, VARIABLE) and had the same experience.

Looking at the debug log, I see I'm getting a return value of 3 from the STATUS DSR call.

I don't get this behaviour if I open a file on DSK1 (or presumably any other local emulated disk.)

Is this a known bug? If so, is there an ETA to fix it? I'm happy to dig into it and do some more debugging if you're hip to pull requests.

**Comment by Rasmus-M** [comment]
The STATUS call wasn't implemented for GDR. I have added a it now. Seems to work.
