### ISSUE TITLE
mouse click not working for TIPI Mouse

### ISSUE THREAD

**Issue by arcadeshopper** [Rasmus-M/js99er-angular#25]
previously worked - when using Stuart's web browser i can move the mouse with the pointer but it won't click on anything

**Comment by Rasmus-M** [comment]
I only have one gamepad to try this on, and it always says "Joystick 0 connected to gamepad 0", so it's difficult to investigate what the problem is.

**Comment by Rasmus-M** [comment]
I made a fast emulation of the mouse in February that doesn't talk to the RPi emulator because that was too slow to be useful. But maybe Stuart's web browser handles the mouse in a way that's not compatible with my fast emulation? I will release version 8.6.3 where I disable the fast emulation.
