### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by pjduplooy1** [Rasmus-M/js99er-angular#4]
Hi Rasmus

I am getting the following build error:

ERROR in Template parse errors:
Unexpected closing tag "mat-select". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (">Hex view</mat-option>
                <mat-option [value]="2">Split view/mat-option>
            [ERROR ->]</mat-select>
        </mat-form-field>
        <span class="margin-right"></span>
"): C:/js99er-angular/src/app/components/debugger/debugger.component.html@11:12
Unexpected closing tag "mat-form-field". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("
                <mat-option [value]="2">Split view/mat-option>
            </mat-select>
        [ERROR ->]</mat-form-field>
        <span class="margin-right"></span>
        <mat-form-field class="memory-"): C:/js99er-angular/src/app/components/debugger/debugger.component.html@12:8
Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("
            <mat-hint>Hexadecimal</mat-hint>
        </mat-form-field>
    [ERROR ->]</div>
</div>
"): C:/js99er-angular/src/app/components/debugger/debugger.component.html@32:4
Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("
        </mat-form-field>
    </div>
[ERROR ->]</div>
"): C:/js99er-angular/src/app/components/debugger/debugger.component.html@33:0

I am using nodejs ltr version12.16.1 npm version 6.14.1, and angular 9.0.4.

npm install worked, but not ng build --prod

Pieter

**Comment by Rasmus-M** [comment]
Sorry, I forgot to push my latest changes.
