### ISSUE TITLE
tipi emulation not working

### ISSUE THREAD

**Issue by arcadeshopper** [Rasmus-M/js99er-angular#53]
setting to full tipi does nothing. nothing in logs about trying to attach, no attempts to connect on the tipi side

**Comment by Rasmus-M** [comment]
It works for me. If you open the developer tools (F12), are there any errors in in the console?

**Comment by arcadeshopper** [comment]
ERROR DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

**Comment by arcadeshopper** [comment]
opening it http works  so it doesn't like having http connections when https://
