### ISSUE TITLE
Restore State causes boot screen to appear

### ISSUE THREAD

**Issue by kyledross** [Rasmus-M/js99er-angular#61]
After clicking the Restore State button to restore a previously-saved state, the video goes back to a damaged TI-99/4A title screen.  The restored program does seem to be running in the background, but the title screen obscures it.

Steps to reproduce (I am using a particular program, I don't know if it affects other programs).

1.  Load Blackjack and Poker
2. Press any key to dismiss console title screen
3. Press 2 to start Blackjack and Poker
4. Start a game of Poker
5. Click the Save State button.
6. Click the Restore State button.  The console title screen will appear and you will not be able to see the running program.

This seems to have been introduced in the 9.0.0 release.

**Comment by Rasmus-M** [comment]
I have restored the old version while investigating this.
