### ISSUE TITLE
SAVE CS1 only works with small programs

### ISSUE THREAD

**Issue by seanwo** [Rasmus-M/js99er-angular#62]
For some reason if the program in memory is above a critical size, get a  I/O ERROR 03 when trying to save it to CS1.

Steps:
1. Load a .TIDisk into js99er (used you website)
2. OLD DSK1.BJ or MERGE DSK1.BLACKJACK
3. LIST 100 (to ensure it loaded properly)
4. SAVE CS1

Result:
* I/O Error 03

If the program loaded into memory is small enough or you just add a few lines by hand, the save to .wav goes as planned.  I am not sure how big is too big.

Here is a .TIDisk I am using with some homebrew programs: https://github.com/seanwo/ti994a/blob/main/github.TIDisk (it contains 2 program files BJ and BS along with the source files that can be merged BLACKJACK and BATTLESHIP) if you want something to reproduce with.

**Comment by Rasmus-M** [comment]
This is not a problem with the emulator but a limitation of the TI-99/4A. You can only save programs up to approximately 12K to tape.

**Comment by seanwo** [comment]
Got it.  I just looked that up here: https://www.digitpress.com/library/manuals/ti994a/ti%20program%20recorder.pdf. Indeed it says the limit is 12K.  Thanks!

**Comment by seanwo** [comment]
closing won't fix.  not a problem.
