### ISSUE TITLE
I can use the "cartridgeURL" to autoload a ROM but not GROM

### ISSUE THREAD

**Issue by seanwo** [Rasmus-M/js99er-angular#63]
So I have my homebrew cart is built as both a ROM and GROM.

When I use the "cartridgeURL" element to specify the cartridge, I can point it to either one and it shows up in the launch menu after the title screen, but only the ROM works.

If I point it to the ROM it will launch.
If I point it to the equivalent GROM it hangs with a long beep.

I have no problem using the toolbar to load either the ROM or GROM manually.

Works:  
```
<js99er config='{"sidePanelVisible": true, "toolbarVisible": true, "cartridgeURL": "mysoftware/BLACKJAC-8.BIN", "settings": {}}'>
```

Does not work:  
```
<js99er config='{"sidePanelVisible": true, "toolbarVisible": true, "cartridgeURL": "mysoftware/BLACKJAC-G.BIN", "settings": {}}'>
```

Testing in development mode

```console
ng serve
```

ROM and GROM:  

https://github.com/seanwo/ti994a/blob/main/BLACKJACK/BLACKJAC-8.BIN
https://github.com/seanwo/ti994a/blob/main/BLACKJACK/BLACKJAC-G.BIN

Is there some setting I need to add?  Thanks!

**Comment by Rasmus-M** [comment]
It should work if you combine the files into an rpk file, see
https://www.ninerpedia.org/wiki/MESS_cartridge_handling#RomPacK_cartridge_images_(RPK)
.

**Comment by seanwo** [comment]
Yes.  That works.  Thank you!
