### ISSUE TITLE
Feature request: API for disk and keyboard

### ISSUE THREAD

**Issue by matthewturk** [Rasmus-M/js99er-angular#65]
Hi!  I'm working on a project that will involve going through an awful lot of TI-99 disks.  Right now my workflow is largely to load the disk, go into extended basic, `OLD DSK1.[programname]` and then start it up.

I was wondering if you would be open to making the js99er interface a bit more script-ready, so that I could potentially automate some or all of this.  Since the time is largely fixed for these operations, simply feeding things into the keyboard buffer would be sufficient.

Would you be open to exploring a scripting tab, perhaps next to "Keyboard" or "Debug" that runs JS that has access to the emulator and display?  I'd also be keen to chip in and try to help out or even take a shot at it, if you think that would be worthwhile.

**Comment by Rasmus-M** [comment]
Sorry for being slow to respond. I don't have any use for scripting myself, so it's not a feature I would be keen on having to keep up to date. However, if you do make a fork and implement this, I would be interested in seeing the result, and maybe I will reconsider.

**Comment by matthewturk** [comment]
@Rasmus-M makes sense -- thank you!  I will see if I can figure something out.  I appreciate the response -- and I'll reopen if I can find a way to make it work and issue a PR or something.
