### ISSUE TITLE
The key ';' and ':' on the on screen keyboard are not working

### ISSUE THREAD

**Issue by sonietje** [Rasmus-M/js99er-angular#66]
Hi,
I'm trying to use the emulator on my iPad and it seems that the key ';' ':' is not working on the on-screen keyboard. 
I tried it on different browsers on my pc and it's the same. I did not try it with older builds.
Thanks for looking into this.
Regards,
Danny

**Comment by Rasmus-M** [comment]
Thanks for reporting. This should be fixed now.
Rasmus

**Comment by sonietje** [comment]
Thanks, I just tested it and it works.
